import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { publishCurrentBranch } from "../src/githubPublish.js";
import type { CommandResult, CommandRunner } from "../src/githubShip.js";

let workdir: string;

beforeEach(() => {
  workdir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "agent-autonomy-publish-")));
});

afterEach(() => {
  fs.rmSync(workdir, { recursive: true, force: true });
});

describe("publishCurrentBranch", () => {
  it("creates a PR for the current branch and records active progress", () => {
    fs.writeFileSync(path.join(workdir, "body.md"), "## Summary\n- test\n");
    const runner = new FakeRunner([
      command({ stdout: "codex/T1500-9-repair\n" }),
      command({ stdout: "https://github.com/rymetry/verdict/pull/107\n" })
    ]);

    const result = publishCurrentBranch({
      projectRoot: workdir,
      title: "feat(T1500-9): repair review integration",
      bodyFile: "body.md",
      taskId: "T1500-9",
      runner
    });

    expect(result).toEqual({
      prNumber: 107,
      url: "https://github.com/rymetry/verdict/pull/107",
      head: "codex/T1500-9-repair",
      base: "main",
      summary: "Created PR #107: https://github.com/rymetry/verdict/pull/107"
    });
    expect(runner.calls[1]).toEqual([
      "gh",
      "pr",
      "create",
      "--title",
      "feat(T1500-9): repair review integration",
      "--body",
      "## Summary\n- test\n",
      "--base",
      "main",
      "--head",
      "codex/T1500-9-repair"
    ]);

    const progress = JSON.parse(
      fs.readFileSync(path.join(workdir, ".agents", "state", "progress.json"), "utf8")
    );
    expect(progress.active).toMatchObject({
      id: "T1500-9",
      pr_number: 107,
      branch: "codex/T1500-9-repair",
      stage: "ship"
    });
  });

  it("generates the title and body from the current branch when omitted", () => {
    const runner = new FakeRunner([
      command({ stdout: "codex/publish-autobody\n" }),
      command({ stdout: "fix: improve publisher defaults\n" }),
      command({ stdout: "origin-main-oid\n" }),
      command({ stdout: "abc123 fix: improve publisher defaults\n" }),
      command({ stdout: " packages/autonomy/src/githubPublish.ts | 42 ++++++++++++++++++++++\n 1 file changed, 42 insertions(+)\n" }),
      command({ stdout: "https://github.com/rymetry/verdict/pull/111\n" })
    ]);

    const result = publishCurrentBranch({
      projectRoot: workdir,
      runner
    });

    expect(result).toMatchObject({
      prNumber: 111,
      head: "codex/publish-autobody",
      base: "main"
    });
    expect(runner.calls[1]).toEqual(["git", "log", "-1", "--pretty=%s"]);
    expect(runner.calls[2]).toEqual(["git", "rev-parse", "--verify", "origin/main"]);
    expect(runner.calls[3]).toEqual(["git", "log", "--oneline", "--no-decorate", "origin/main...codex/publish-autobody"]);
    expect(runner.calls[4]).toEqual(["git", "diff", "--stat", "origin/main...codex/publish-autobody"]);
    expect(runner.calls[5]).toEqual([
      "gh",
      "pr",
      "create",
      "--title",
      "fix: improve publisher defaults",
      "--body",
      [
        "## Summary",
        "- abc123 fix: improve publisher defaults",
        "",
        "## Why-this-PR",
        "- Generated by the autonomy publisher from the current branch diff.",
        "",
        "## Test plan",
        "- Not run by publisher. See commit and CI evidence for verification.",
        "",
        "## Changed files",
        "- packages/autonomy/src/githubPublish.ts | 42 ++++++++++++++++++++++",
        "- 1 file changed, 42 insertions(+)",
        "",
        "## NOT-in-this-PR",
        "- No unrelated changes were intentionally included.",
        ""
      ].join("\n"),
      "--base",
      "main",
      "--head",
      "codex/publish-autobody"
    ]);
  });

  it("falls back to the local base branch when the remote base ref is unavailable", () => {
    const runner = new FakeRunner([
      command({ stdout: "codex/local-base\n" }),
      command({ stdout: "fix: local base fallback\n" }),
      command({ exitCode: 1, stderr: "unknown revision\n" }),
      command({ stdout: "def456 fix: local base fallback\n" }),
      command({ stdout: " packages/autonomy/src/githubPublish.ts | 12 ++++++\n" }),
      command({ stdout: "https://github.com/rymetry/verdict/pull/112\n" })
    ]);

    publishCurrentBranch({
      projectRoot: workdir,
      runner
    });

    expect(runner.calls[3]).toEqual(["git", "log", "--oneline", "--no-decorate", "main...codex/local-base"]);
    expect(runner.calls[4]).toEqual(["git", "diff", "--stat", "main...codex/local-base"]);
  });
});

function command(partial: Partial<CommandResult>): CommandResult {
  return {
    exitCode: partial.exitCode ?? 0,
    stdout: partial.stdout ?? "",
    stderr: partial.stderr ?? ""
  };
}

class FakeRunner implements CommandRunner {
  readonly calls: string[][] = [];

  constructor(private readonly results: CommandResult[]) {}

  run(commandName: string, args: readonly string[]): CommandResult {
    this.calls.push([commandName, ...args]);
    const result = this.results.shift();
    if (!result) {
      throw new Error(`Unexpected command: ${commandName} ${args.join(" ")}`);
    }
    return result;
  }
}
